### ISSUE TITLE
Warnings as errors

### ISSUE THREAD

**Issue by patriksvensson** [statiqdev/Statiq.Framework#101]
Yesterday I modified a pipeline and accidentally wrote the same document to the same output. Statiq noticed and warned me, and luckily I saw the warning in the output.

It would be great if it were possible to fail a build on warnings. Either as part of the bootstrapper itself, or as a parameter to Statiq.

#### Bootstrapper approach:

```csharp
private static Task<int> Main(string[] args)
{
    return Bootstrapper
        .Factory
        .CreateDefault(args)
        .TreatWarningsAsErrors()
        .RunAsync();
}
```

#### Argument approach:

```shell
> dotnet run -- --strict
```

**Comment by daveaglick** [comment]
I really like this suggestion - will try to get it into the next release.

**Comment by daveaglick** [comment]
Added a CLI `--strict <LEVEL>` option. For example, setting it to `--strict Warning` will produce a message and fail generation for warnings and above.
