### ISSUE TITLE
Custom commands are added twice

### ISSUE THREAD

**Issue by patriksvensson** [statiqdev/Statiq.Framework#103]
![image](https://user-images.githubusercontent.com/357872/82733610-39557f80-9d15-11ea-9df5-69efccc8fd69.png)

**Comment by daveaglick** [comment]
How was the command added (with reflection over implemented command classes or with the Bootstrapper `.AddDelegateCommand()` method)?

**Comment by patriksvensson** [comment]
Didn't do anything at all. Just using Statiq.Framework and added a new command class. Statiq found it by magic.
