### ISSUE TITLE
SymbolId is not unique when nested types have the same name

### ISSUE THREAD

**Issue by ociaw** [statiqdev/Statiq.Framework#116]
Disclaimer: I'm encountering this problem with Wyam, but I believe applies to Statiq as well.

For example, in the following code, both nested classes will be assigned the symbol id `Factory`, despite them living in the same namespace.

```
public class Namespace.Foo
{
    public class Factory {}
}
public class Namespace.Bar
{
    public class Factory {}
}
```

I think this could be fixed fairly easily in `ISymbolExtensions.GetId` by checking `ISymbol.ContainingType` - if it's null, use the original behavior, otherwise
use `GetFullName` instead of `ISymbol.MetadataName`.

i.e. Replace this:
https://github.com/statiqdev/Statiq.Framework/blob/c80ebe82a034f66ccc270d6c0c94570c868e08af/src/extensions/Statiq.CodeAnalysis/ISymbolExtensions.cs#L25

with this:

```
char[] id = symbol.ContainingType == null ?
            symbol.MetadataName.ToCharArray() :
            GetFullName(symbol).ToCharArray();
```

I'd submit a PR, but I'm not sure how easy it would be to set up an environment I can test this in Statiq.

**Comment by ociaw** [comment]
Thinking about it, just calling `GetId` recursively might work better.
```
char[] id = symbol.MetadataName.ToCharArray();
if (symbol.ContainingType != null)
{
    id = symbol.ContainingSymbol.GetId() + "." + id;
}
```

**Comment by daveaglick** [comment]
Good catch - we definitely want unique IDs in case they're used as keys in a lookup or something. I'll classify this as a bug and look at fixing in the `AnalyzeCSharp` module.

**Comment by daveaglick** [comment]
I was able to repro this in a unit test and fix with a recursive `GetId()` approach very similar to what you suggested. Thanks again for the great bug report!
