### ISSUE TITLE
MirrorResources should remove "integrity" and "crossorigin" attributes

### ISSUE THREAD

**Issue by sytexa-julia** [statiqdev/Statiq.Framework#127]
Once a script or stylesheet is mirrored, the sub-resource integrity attributes `integrity` and `crossorigin` are not needed (and break the site when viewing locally... in Chromium at least.)

**Comment by daveaglick** [comment]
Good call! Totally agree the `MirrorResources` module should remove those when (and only when) mirroring locally.

**Comment by daveaglick** [comment]
Now resolved and will ship in the next release.
