### ISSUE TITLE
Relative link validation doesn't appear to be working correctly

### ISSUE THREAD

**Issue by gep13** [statiqdev/Statiq.Framework#128]
When running Statiq, I am seeing that relative links, that are working when running the site, are being flagged as invalid.

For example:

![image](https://user-images.githubusercontent.com/1271146/94372534-7338f700-00f6-11eb-8aa8-898b12824922.png)

Clicking the `Chocolatey Configuration` link correctly goes to the page, but it is being flagged in the output as invalid.

Any ideas on what is going on here?

This seems to happen both for links that start with `../` (i.e. one folder up) and also links that start with `./` (i.e. within the same folder)

**Comment by gep13** [comment]
Going to mention @mholo65 here, as he mentioned that he would be up for tackling this issue 😄

**Comment by mholo65** [comment]
HACKTOBERFEST!!!

**Comment by daveaglick** [comment]
REJECTED

**Comment by daveaglick** [comment]
(but seriously, I'll be happy to give you all the Hacktoberfest magic Internet points you want in exchange for sweet, sweet code)

**Comment by patriksvensson** [comment]
@daveaglick How about this. Instead of @mholo65 sends a PR with features, bugfixes and other boring stuff, how about I submit a PR where I convert all your whitespace to tabs and give your project a new name?

Think about it.

**Comment by mholo65** [comment]
@daveaglick I already have a failing test ;)
![image](https://user-images.githubusercontent.com/7863439/94733838-0b421500-0371-11eb-9dab-9461c0049c37.png)

**Comment by mholo65** [comment]
> 
> 
> @daveaglick How about this. Instead of @mholo65 sends a PR with features, bugfixes and other boring stuff, how about I submit a PR where I convert all your whitespace to tabs and give your project a new name?
> 
> Think about it.

@daveaglick, I can also send a PR which changes the style guide *slightly*.... HOW ABOUT FIXING THESE EXPLICITLY TYPED LOCAL VARIABLES!?!?!

**Comment by daveaglick** [comment]
![](https://media0.giphy.com/media/l4FGonHrc1YpKi8G4/giphy.gif)
