### ISSUE TITLE
Feeds, Highlight and HTML package dependend on outdated AngleSharp version

### ISSUE THREAD

**Issue by alanta** [statiqdev/Statiq.Framework#135]
The Statiq.Feeds, Statiq.Highlight and Statiq.Html packages depend on AngleSharp 0.9.10 but the current version of AngleSharp (0.14) is incompatible with that version due to a change in namespaces. This causes runtime exceptions when Statiq is used with other libraries using newer versions of AngleSharp.

See also this related issue alanta/kontent.statiq#15

I've tried upgrading Statiq.Framework to 0.14 and it compiles and tests pass with very little effort. I'll put up a PR.

**Comment by daveaglick** [comment]
That would be awesome, thanks! I'd be happy to pull in an updated version of AngleSharp. I think we've got pretty good test coverage in most of the areas AngleSharp is used, so if tests pass I'd guess we're good to go.

**Comment by daveaglick** [comment]
Resolved by #136
