### ISSUE TITLE
How to access IConfiguration in ConfigureServices?

### ISSUE THREAD

**Issue by petrsvihlik** [statiqdev/Statiq.Framework#137]
After [this](https://github.com/statiqdev/Statiq.Framework/commit/294e7de98b5d1f66c902fa863614bc61569859c7#diff-1a39b8a3b301dd38266639945f36632f) change, what's the best way to access the `IConfiguration` (`IConfigurationRoot`) object in `ConfigureServices()`?

Suppose I had code like this:
```c#
await Bootstrapper
                .Factory
                .CreateDefault(args)
                .ConfigureServices((services, config) =>
                {
                    services.AddDeliveryClient(config);
                })
```

Now I need to temporarily overcome this issue by building the service provider:
```c#
await Bootstrapper
                .Factory
                .CreateDefault(args)
                .ConfigureServices((services, config) =>
                {
                    // config is now ISettings so I need to retrieve IConfiguration differently
                    var cfg = services.BuildServiceProvider().GetRequiredService<IConfiguration>();
                    services.AddDeliveryClient(cfg);
                })
```

cc @alanta

**Comment by alanta** [comment]
You can cast the settings object passed in to IConfiguration:

```c#                
.ConfigureServices((services, settings) =>
{
  services.AddSingleton<ITypeProvider, CustomTypeProvider>();
  services.AddSingleton<IContentLinkUrlResolver, CustomContentLinkUrlResolver>();
  services.AddDeliveryClient((IConfiguration)settings);
})
```

**Comment by petrsvihlik** [comment]
@alanta ok, that didn't occur to me... I see it now `Settings : ISettings, IConfiguration` cool!

**Comment by daveaglick** [comment]
@alanta is exactly right - there used to be multiple classes containing settings/configuration and that was really confusing so they're combined into one now (which is also fun because it means we can get a `IConfiguration` from `IExecutionContext.GetRequiredService<IConfiguration>()` and it'll contain _all_ the settings, including those set manually from the Bootstrapper because it actually is the settings object).

**Comment by petrsvihlik** [comment]
right, perfect :) definitely a good point for a getting started guide ;) I'm taking a mental note
