### ISSUE TITLE
Question: How to add custom configuration sources?

### ISSUE THREAD

**Issue by petrsvihlik** [statiqdev/Statiq.Framework#139]
Is there a way in Statiq to add a specific `IConfigurationProvider`/`IConfigurationSource`? (like user secrets, azure key vault, or a completely custom one...?)

Motivation: I like to keep my keys safe so I tend to store them in the user secrets on a local machine and in the env variables on a production machine.

**Comment by petrsvihlik** [comment]
`.BuildConfiguration(cfg => cfg.AddUserSecrets<Program>())`

**Comment by daveaglick** [comment]
Awesome, glad you figured it out before I had a chance to respond - any ASPNET configuration provider should be able to be added this way.
