### ISSUE TITLE
Is there a way to specify pipeline name with default pipeline detection

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq.Framework#141]
I would like to know if it is possible to customize the pipeline name when a pipeline is added with the default detection mechanism (I'm defining my pipelines by creating classes inheriting from `Pipeline`). 

With this method the pipelines are named after the classes, but I would like to have a more meaningful name, like it's possible by using `BuildPipeline` on the bootstrapper. I would also like to be able to reference my pipelines without having to reference the class directly (in `FromPipeline` by example).

**Comment by k94ll13nn3** [comment]
Found the solution, didn't know there was an `INamedPipiline` interface!

**Comment by daveaglick** [comment]
Yeah, one of the (many) things that needs better documentation.
