### ISSUE TITLE
TagHelpers don't work

### ISSUE THREAD

**Issue by petrsvihlik** [statiqdev/Statiq.Framework#143]
Neither the `Microsoft.AspNetCore.Mvc.TagHelpers` nor [custom](https://github.com/petrsvihlik/statiq-starter-kontent-lumen/blob/master/TagHelpers/GistTagHelper.cs) TagHelpers get resolved.

I think the problem might be that the `CompilationTagHelperFeature` is not part of the `RazorProjectEngine.EngineFeatures` collection.

When I debug the source of `Statiq.Framework`, the [`Statiq.Razor.Tests.RenderRazorFixture.AlternateModel`](https://github.com/statiqdev/Statiq.Framework/blob/8988be57887fe912b7969366269f8bea58a2278f/tests/extensions/Statiq.Razor.Tests/RenderRazorFixture.cs#L110) will try to create the `RazorCompiler` which tries to resolve the `RazorProjectEngine`:
https://github.com/statiqdev/Statiq.Framework/blob/6c833bb2087cf1215cbba4b87dd53d8c79636e9e/src/extensions/Statiq.Razor/RazorCompiler.cs#L84

The call to:
https://github.com/statiqdev/Statiq.Framework/blob/6c833bb2087cf1215cbba4b87dd53d8c79636e9e/src/extensions/Statiq.Razor/IServiceCollectionExtensions.cs#L77

**should** result in adding the `CompilationTagHelperFeature`

https://github.com/dotnet/aspnetcore/blob/24b34d720366af99b20d1736b96a9ab184d37c31/src/Mvc/Mvc.Razor.RuntimeCompilation/src/DependencyInjection/RazorRuntimeCompilationMvcCoreBuilderExtensions.cs#L97

but when I check the collection of features of the resolved `razorProjectEngine`, it doesn't contain it.

**Comment by daveaglick** [comment]
I added a test for tag helpers (I like to add failing tests before doing work on bugs) and was actually a bit surprised to find they worked out of the box!

![image](https://user-images.githubusercontent.com/1020407/99149673-8a5b8600-265d-11eb-8234-c7e1b0296c50.png)

At a minimum it looks like the default `Microsoft.AspNetCore.Mvc.TagHelpers` can be imported. So now I'm wondering where the disconnect is between the behavior you observed and the behavior in the test.

Did you have the `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers` syntax either in your Razor file or in a `_ViewImports.cshtml` file?

**Comment by daveaglick** [comment]
Also appears custom tag helpers work out of the box:

![image](https://user-images.githubusercontent.com/1020407/99150023-bd067e00-265f-11eb-8607-cad1daaeab6b.png)

**Comment by daveaglick** [comment]
One thing we could consider is adding tag helpers to the scope via the `RenderRazor` module instead of the Razor file or a `_ViewImports.cshtml` file. My guess is this would look something like the recent work on view data by adding tag helpers to the `ViewContext` (hopefully that's it - if the set of tag helpers isn't exposed via public API anywhere it might get trickier).

In any event, I'd want to make sure tag helpers are always opt-in (as opposed to adding any automatically) given that they can "take over" normal HTML elements. Though I guess this is up for debate - perhaps the expectation of .NET developers is that tag helpers are available in their Razor views by default and not having them is the unexpected behavior.

**Comment by alanta** [comment]
I'm flabbergasted... I tried to get this to work a couple of times since June but couldn't. Tried it again after reading this and now it  works as expected. Tried a couple of different scenarios, it just works  ¯\_(ツ)_/¯

**Comment by petrsvihlik** [comment]
yup, it all works now...I gave it a few more tries and there were two problems with my code:
- the `HtmlTargetElement` was too strict in my case so the tag helper wasn't being applied
- I used namespace instead of the assembly name in the `@addTagHelper` directive

however, I don't know what was I doing wrong the last time when I was trying the built-in asp.net tag helpers...they didn't work and now they seem to work too...

anyways, I'm glad that we have confirmed that the tag helpers work :) closing the issue...

**Comment by daveaglick** [comment]
:) no problem, this caused me to add some tests around tag helpers, so that's good anyway!
