### ISSUE TITLE
Provide ViewData for Razor views

### ISSUE THREAD

**Issue by alanta** [statiqdev/Statiq.Framework#145]
In addition to providing a (typed) model for rendering Razor views, it would be great if it was possible to provide ViewData. 
Many sites use view data to pass along additional data such as site configuration, SEO data, page title etc.

It could look something like this:

```c#
new RenderRazor()
   .WithModel(Config.FromDocument((doc,ctx) => new MyContentModel(doc))
   .WithViewData("Metadata", Config.FromValue(myMetaData))
```

It would be great if multiple ViewData properties can be supplied.

**Comment by daveaglick** [comment]
Resolved by #146
