### ISSUE TITLE
Right-To-Left support

### ISSUE THREAD

**Issue by encrypt0r** [statiqdev/Statiq.Framework#15]
Hi, I was wondering what would it take to add a new module to wyam to support RTL content. The module needs to add dir="rtl" attribute to all elements that start with RTL characters and align="right" to tables, RTL characters are specified by section D of RFC3454. For more information, please take a look at lunet-io/markdig#239.

It would also be useful if the module adds a css class to these html elements so that they can be styled (most probably their font characteristics) separately.

I am willing to create a PR, but might need some help and guidance.

**Comment by encrypt0r** [comment]
Hey @daveaglick is now a good time to start working on the globalization module?

**Comment by daveaglick** [comment]
@encrypt0r Yeah! The Statiq API is becoming pretty stable. I'm still releasing it as alphas just in case I need to change a few things as I finish out my push towards 1.0, but for the most part I'm avoiding breaks going forward. One thing you'll notice is that there are _a bunch_ of `Module` base classes - using one of those should make the process of writing modules much easier (you'll also notice most of the built-in modules also use the base module classes so they're good examples).

As always, feel free to hit me up if you've got any questions.

**Comment by daveaglick** [comment]
One other thought - the new module should probably go in the `Statiq.Html` extension library. Something like [MirrorResources](https://github.com/statiqdev/Statiq.Framework/blob/master/src/extensions/Statiq.Html/MirrorResources.cs) is probably similar given that it rewrites HTML (though your RTL module obviously wouldn't be doing other stuff that module does like make network calls).

**Comment by encrypt0r** [comment]
@daveaglick thanks! I'll take a look and keep you updated
