### ISSUE TITLE
Certain editors throw file access error on live preview

### ISSUE THREAD

**Issue by JamesThorpe** [statiqdev/Statiq.Framework#151]
When editing files in VSCode or Notepad++ with the live preview running, I see the following error on each save:

> [ERRO] Inputs/Process » ExecuteIf » ExtractFrontMatter » [D:/dev/teststatiq/TestSite/input/test.md => test.md] The process cannot access the file 'D:\dev\teststatiq\TestSite\input\test.md' because it is being used by another process.

This is consistent on every save from vscode or notepad++, but saving a file in notepad causes the rebuild to happen without issue.

I've replicated this on a fresh project, using [just these steps](https://statiq.dev/web/):

```
dotnet new console --name TestSite
cd TestSite
dotnet add package Statiq.Web --version 1.0.0-beta.13
code .
```
Updated Program.cs as per the docs, and added `input/test.md`

```
dotnet run
```
Verified that the file in `output` is generated fine.

```
dotnet run -- preview
```

Edit page in vscode and save, I see the error.  Immediately edit using notepad, no error.

Other info:
VSCode: 1.51.1
Windows 10: 19041
Dotnet: 5.0.100

The full error with `-l Debug` enabled:

>     [ERRO] Inputs/Process » ExecuteIf » ExtractFrontMatter » [D:/dev/teststatiq/TestSite/input/test.md => test.md] The process cannot access the file 'D:\dev\teststatiq\TestSite\input\test.md' because it is being used by another process.
>     [DBUG] Exception while executing pipeline Inputs/Process: System.IO.IOException: The process cannot access the file 'D:\dev\teststatiq\TestSite\input\test.md' because it is being used by another process.
>        at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
>        at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
>        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
>        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
>        at Statiq.Core.LocalFile.OpenRead()
>        at Statiq.Common.FileContent.GetStream()
>        at Statiq.Common.IDocumentExtensions.GetContentStream(IDocument document)
>        at Statiq.Common.IDocumentExtensions.GetContentStringAsync(IDocument document)
>        at Statiq.Core.ExtractFrontMatter.ExecuteInputAsync(IDocument input, IExecutionContext context)
>        at Statiq.Common.Module.ExecuteInputFuncAsync(IDocument input, IExecutionContext context, Func`3 executeFunc)

**Comment by daveaglick** [comment]
Thanks for the details - first thing that jumps out is .NET 5. I haven't done a ton of testing under that runtime yet, so maybe that's a significant difference.

**Comment by JamesThorpe** [comment]
That's it!  I added a `global.json`:

```
{
  "sdk": {
    "version": "3.1.402"
  }
}
```
Updated the csproj to target netcoreapp3.1, and with no other changes it's now working as expected.

**Comment by JamesThorpe** [comment]
Sorry... spoke too soon. It worked on the first edit, but not subsequent ones...

**Comment by JamesThorpe** [comment]
The exact same steps (which I'm sure many other people, including yourself, have probably run many times!) worked fine on another machine I have to hand.  Same windows build, but has never had .net 5 on it, so even though I'm targetting 3 above, maybe it's still affecting it somehow...?

I have one more machine I can test on later, which does have 5 on it already.

**Comment by JamesThorpe** [comment]
On the other PC, (Windows 10, build 19042), I see the error but only when saving in VSCode, and not when saving in notepad++ or notepad.  

This one is dotnet 5.0.100, it doesn't have 3.x, the only other ones installed at the moment are 2.x.

**Comment by daveaglick** [comment]
Thanks a lot for following up, these are great data points. I'm going to try playing around with VMs and different .NET SDKs to see if I can reproduce the problem - the SDK version might be a total red herring, but seems like a good place to start.

**Comment by daveaglick** [comment]
I still haven't been able to reproduce this locally, but I have observed it on other systems now. The behavior is exactly as you describe. At one point VS Code even complained of a locked file _it_ was saving (which may be a clue that there's some interesting back-and-forth going on with multiple file system events).

The next release due out today includes a rewrite of the file system watcher to include some event debouncing. I needed it anyway, but it might help with this problem as well 🤞.

**Comment by JamesThorpe** [comment]
Just as another data point - I just noticed that beta 14 was out a week or so ago (vs the 13 I was using) and updated to it.  It seems that in that version it "works" in that it fails as before, but then attempts to do the whole thing again immediately?  It means the live reload in the browser still breaks (on the first attempt), but manually refreshing then loads up the site.

I'll give the next release a go when it's out/I have a few minutes!

**Comment by daveaglick** [comment]
New version is out now, go ahead and take it for a spin whenever you get the chance. The double execution on write regression is actually why I added the throttling in the first place (it got introduced when I reworked the preview command to support the as-yet-undocumented REPL), so hopefully we'll fix both problems at once!

**Comment by JamesThorpe** [comment]
Same error I'm afraid, the only changes I made to the test project from before are:

```
dotnet add package Statiq.Web --version 1.0.0-beta.15
dotnet run -- preview
```

So this is still targetting 3.1, rather than 5.  Save file in VSCode or Notepad++, same error/stacktrace, Notepad remains fine.  The double execution has gone again in beta 15 though.

**Comment by daveaglick** [comment]
Doh! Well at least the regression is fixed. I'll start focusing more attention on figuring this out, hopefully I'll get to the bottom of it soon.

**Comment by JamesThorpe** [comment]
Unsure if there's anything else I can do to help, but if you think there is, I'm happy to try!

**Comment by daveaglick** [comment]
I'm on to something, almost positive this is related somehow to the .NET runtime. I tried unsuccessfully over probably 100 executions to trigger the lock error with no joy. Then I (finally) installed the .NET 5 SDK onto my main development box, confirmed the `dotnet` muxer had switched to the .NET 5 runtime, and was able to reproduce within 2 or 3 executions.

**Comment by daveaglick** [comment]
Caught red-handed!

![image](https://user-images.githubusercontent.com/1020407/100785104-316e4a80-33de-11eb-8485-5e469c8d585e.png)

**Comment by daveaglick** [comment]
Looking over the process operations on the file, nothing jumps out as egregious. Looks like it's just the occasional bad timing:

- The editor initiates it's write sequence which might start with some information gathering operations depending on the editor (probably why this is editor dependent).
- That fires the Statiq file watcher, which starts execution _immediately_ and debounces following file operations.
- Normally the editor will then finish it's write sequence before Statiq gets to the part where it needs to read the file...
- ...but if Statiq beats the editor, it'll try to obtain a read lock on the file while the editor still holds a write lock and 💥

The whole .NET 5 vs. not is likely just due to .NET 5 being faster and so the probability of Statiq getting to the read lock request while the editor still holds the write lock is greater. I.e., .NET Core 3.x was slow enough that this problem existed, we were just unlikely to trigger it.

Best mitigation I can think of at the moment is to add an extra wait to the first file system event that fires, maybe 500ms or so. That should give the editor time to get out of the way without perceptibly delaying re-execution. And just in case it doesn't, I think I can also wrap the `FileStream` creation where the exception is thrown in a retry policy with some kind of fall-off so we'll wait for the editor if it's still holding a lock.

I'll probably try to get another patch release out this afternoon with this fix.

**Comment by daveaglick** [comment]
Managed to ship another release with some of these timing changes. Once again, if you don't mind taking it for a spin and seeing if it resolves things I'd be grateful! I'm no longer able to trigger the problem with these changes, but you seem to be able to reproduce pretty consistently.

**Comment by JamesThorpe** [comment]
Initial testing looks good to me!  The extra delay before the processing kicks in is I think noticeable, but only because I'm watching for it - it's still plenty fast enough for the purpose.  And thanks for the introduction to Polly... I think I can find some uses for that myself...!

**Comment by daveaglick** [comment]
Yey! Guess we can put this one to rest for now. If it pops back up, please reopen this issue and I'll continue working the problem.

And yeah, Polly is a great little library. One of those ones I tend to add to every project because it does one thing really well that we usually have to do all the time anyway.
