### ISSUE TITLE
LinkRoot is duplicated in sitemap.xml.

### ISSUE THREAD

**Issue by taks** [statiqdev/Statiq.Framework#158]
The LinkRoot value is duplicated in the output of sitemap.xml like `<loc>http://host/LinkRoot/LinkRoot</loc>`.

**Comment by daveaglick** [comment]
I am unable to replicate this on several sample sites, so I suspect there might be an interplay between your `LinkRoot` setting and the files (and their destination). Are you using the `GenerateSitemap` module directly or is this happening when using Statiq Web?

**Comment by taks** [comment]
I'm using Statiq Web.
I create a sample project for this issue at https://github.com/taks/Statiq.Web.Sample.

**Comment by daveaglick** [comment]
Awesome! Thanks a ton - a repro will make this much easier to track down.

**Comment by taks** [comment]
I check `GenerateSitemap` and find out why the LinkRoots are duplicated.
The cause is that `GetLink` is called twice in the following.

https://github.com/statiqdev/Statiq.Framework/blob/556226db5255bb7f1e279e8a15ea250e47180298/src/core/Statiq.Core/Modules/Content/GenerateSitemap.cs#L95

https://github.com/statiqdev/Statiq.Framework/blob/556226db5255bb7f1e279e8a15ea250e47180298/src/core/Statiq.Core/Modules/Content/GenerateSitemap.cs#L114

**Comment by daveaglick** [comment]
Resolved by #193 - fix will go out with the next release in a few days.
