### ISSUE TITLE
Preview command on MacOS require repl input to trigger re-exectuion

### ISSUE THREAD

**Issue by devlead** [statiqdev/Statiq.Framework#182]
Om MacOS Sometimes changes seem to be picked up by Statiq when running preview command, but a site pipeline regeneration starts first after REPL gets some console input i.e. a left arrow.

**Comment by daveaglick** [comment]
For future reference, a `Task.Run()` kicks off a console thread that just sits there and listens for `Console.ReadKey()` continually to intercept all key presses - the intent is that it doesn't interfere with anything else, it buffers key presses until the enter key is pressed and then sends those back to the main thread through a callback.

There's some question as to what's behind the different behavior on MacOS, but it could be either that the `Console.ReadKey()` does more extensive blocking than it does on other platforms (I.e. by blocking other threads) or that `Task.Run()` doesn't actually spawn a new thread as expected.
