### ISSUE TITLE
Release for .NET 6

### ISSUE THREAD

**Issue by intellectronica** [statiqdev/Statiq.Framework#219]
The current release of .NET isn't supported, so it's not possible to install the package and use it with the current tooling. From the commit history it looks like whatever problems there were which necessitated fixing to .NET 5 are already fixed, but there's no release available yet.

**Comment by daveaglick** [comment]
Can you expand on this a bit? Statiq targets .NET Core 3.1 which is a [Long Term Support release](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) and won't be officially unsupported until December 2022 (and even then will notionally continue to work with tooling, etc.). Not to mention there's a high degree of backwards compatibility guarantees in the entire .NET platform. I know many users who are happily running Statiq under projects that target .NET 6 or on the .NET 6 runtime.

Statiq will of course migrate to target .NET 6 at some point, but it likely won't be until spring or summer of next year after we reach a 1.0 milestone.

Are you encountering any specific errors?

**Comment by intellectronica** [comment]
Oh, maybe I just don't understand how to install it correctly. This is what I get:
```> dotnet add package Statiq.App --version 1.0.0-beta.52
  Determining projects to restore...
  Writing C:\Users\...\AppData\Local\Temp\tmp5C49.tmp
info : Adding PackageReference for package 'Statiq.App' into project 'C:\Users\...\...\....csproj'.
info : Restoring packages for C:\Users\...\...\....csproj...
error: NU1100: Unable to resolve 'Statiq.App (>= 1.0.0-beta.52)' for 'net6.0'.
error: Package 'Statiq.App' is incompatible with 'all' frameworks in project 'C:\Users\...\...\....csproj'.
```

**Comment by intellectronica** [comment]
OK, nvm, it was just an issue with my setup (fresh .NET 6.0). This fixed things:
```
dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json
```

**Comment by daveaglick** [comment]
That's very odd - are you able to paste the output of `dotnet --info` here as well as what's in your `.csproj` file? This is what you should see (just ran this to verify everything works):

![image](https://user-images.githubusercontent.com/1020407/147004041-20d972ed-9ab0-46ed-906c-504a96343a4c.png)

![image](https://user-images.githubusercontent.com/1020407/147004050-a7c82766-6607-415d-b707-ca9ffbf9640d.png)

**Comment by daveaglick** [comment]
Ah perfect! Glad you figured it out :)
