### ISSUE TITLE
Add comment style front matter for Razor

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq.Framework#231]
See https://github.com/statiqdev/Discussions/discussions/132

Note that the syntax should clearly indicate front matter over other top-of-file block comments. I.e.

```
@*---
Front: matter
---*@
```

As part of this change, since we're establishing a pattern, the [script](https://www.statiq.dev/web/content-and-data/scripts#front-matter) front matter comment support should be changed to require a similar dash style delimiter.

**Comment by daveaglick** [comment]
To that end I wonder if it's possible to generalize this and look for `---` at the end of the first line of a file and at the start of a following line (with the reverse of the first line extra characters?).

**Comment by daveaglick** [comment]
So it turns out changing the module to accept two different styles of delimiters ("normal" and the proposed comment style) is going to be tricky. It would also be nice to support multiple delimiter sets in a single module so as more kinds of delimiters are supported we don't have to continue parsing the file into a string array each time. Being able to pass in front matter delimiter data as a single string would be nice too so we can add a setting to describe additional front matter delimiters.

I think the answer to all these is to support RegEx for specifying how to find front matter. That leaves a question of what to do about existing code. Should the current way of specifying also be accepted (and maybe converted to a RegEx)?

**Comment by daveaglick** [comment]
This is now done and will go out with the next Statiq Web release, which will allow syntax like what's in the description of this issue for defining front matter in Razor files (in addition to HTML comment syntax like `<!---` as well).

In Statiq Framework front matter is extracted by the `ExtractFrontMatter` module which now accepts regular expressions. When using the `ExtractFrontMatter` module in Statiq Framework without predefined front matter handling like Statiq Web provides, the following regular expressing can be used for Razor block comment front matter: `\A(?:^\r*@\*-+[^\S\n]*$\r?\n)(.*?)(?:^\r*-+\*@[^\S\n]*$\r?\n)`.

**Comment by daveaglick** [comment]
What's the relationship between `base.cshtml` and `post.cshtml`? If `base.html` is a Razor layout, then the document metadata should still be available through the `Document` page property just like the actual page.

**Comment by ror3d** [comment]
Both are layouts.

A post will have `Layout: @"_layouts/post.cshtml"`, whereas in the `post.cshtml` file I have
```
@{
    Layout = @"_layouts/base.cshtml";
}
```

**Comment by ror3d** [comment]
Almost, but I was trying to set the frontmatter from the template, which I think is what's not supported in this manner.

`input/_OuterLayout.cshtml`

```
<body> 
<div>Outer layout color: @Document.GetString("Color")</div>
@RenderBody()
</body>
```

`input/_InnerLayout.cshtml`:

```
@*---
Color: Blue
---*@
@{
    Layout = @"/_OuterLayout.cshtml";
}
<div>Inner layout color: @Document.GetString("Color")</div>
@RenderBody()
```

`input/Test.cshtml`:

```
@{
    Layout = @"/_InnerLayout.cshtml";
}
<div>Test color: @Document.GetString("Color")</div>
```

Expected output:

```
<body> 
<div>Outer layout color: Blue</div>
<div>Inner layout color: Blue</div>
<div>Test color: Blue</div>
</body>
```

**Comment by daveaglick** [comment]
> I was trying to set the frontmatter from the template, which I think is what's not supported in this manner

Ah, yes - you're exactly right. The layout files don't get processed in the same way so they can't set front matter (there's not even a Statiq document for them, they become "part" of the contained page during rendering).

Glad you figured out an approach that will (mostly) work though!
