### ISSUE TITLE
Code formatting reports unknown language for `plaintext`

### ISSUE THREAD

**Issue by girlpunk** [statiqdev/Statiq.Framework#269]
As per highlight.js's [supported languages](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md), `plaintext` is a valid language for highlighting, however Statiq reports a warning when using this

```
[WARN] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteConfig » HighlightCode » Exception while highlighting source code: Error: Unknown language: "text"
   at highlight-all.js:498:7
```

**Comment by daveaglick** [comment]
The version of highlight.js Statiq uses for generation-time highlighting is relatively old and required some workarounds to build so it could be run from inside .NET: https://github.com/statiqdev/Statiq.Framework/blob/main/src/extensions/Statiq.Highlight/regenerating-highlight-all.js.md. I took a quick look through [the code](https://github.com/statiqdev/Statiq.Framework/blob/main/src/extensions/Statiq.Highlight/highlight-all.js) and sure enough, `txt`, `plaintext`, and `text` are all not current aliases. Those may have been added after our internal copy was produced.

I can see about updating our version of `highlight.js`.

**Comment by daveaglick** [comment]
Unfortunately it wasn't as easy as just running the same commands I used initially. As often happens, the npm packages and node ecosystem has moved under us and I'll need to figure out how to regenerate the highlight.js file from scratch. That could take some time.

**Comment by girlpunk** [comment]
If it helps, it looks like there's a special case to handle plaintext, which should be getting detected at [highlight-all.js:623](https://github.com/statiqdev/Statiq.Framework/blob/625bd4754bf14f3c6a860587c6d747f4850b1c13/src/extensions/Statiq.Highlight/highlight-all.js#LL623C17-L623C17)

**Comment by daveaglick** [comment]
It took a little hacking, but I got this figured out. Highlighting `txt` should work in the next release of Statiq (probably next week some time).

**Comment by girlpunk** [comment]
Hi, any chance on a release for this? Thanks

**Comment by daveaglick** [comment]
A new release just went out! Sorry for the super-long delay. I had thought I released this already and then got swamped (still am, but managed to get a new release out the door).
