### ISSUE TITLE
Change globbing patterns to use brackets instead of braces

### ISSUE THREAD

**Issue by daveaglick** [statiqdev/Statiq.Framework#35]
Globbing patterns can currently accept braces to indicate expansion: `*.{xml,txt}`. This has potential to conflict with string interpolation which also uses braces. One or the other could be escaped, but that's counter-intuitive and not very friendly. Instead the globbing patterns could be changed to use brackets instead which keeps similar semantics: `*.[xml,txt]`.

**Comment by daveaglick** [comment]
Not going to change this, it's easy enough to escape the braces in interpolated strings with double braces and changing it now would be a pretty big break for everyone.

**Comment by patriksvensson** [comment]
Good, because `{bar,qux}` and `[bar,qux]` would have completely different meanings for extglob patterns.
The first one means `Any of these words` while the other means `Any of these characters` (including the comma).

**Comment by daveaglick** [comment]
Interesting, I wasn't even aware of extglob until just now! Glad I accidentally ended up with something similar to an established convention :). If a .NET library is ever written with extglob support, it looks like we could consider adopting it without too many changes too.

**Comment by patriksvensson** [comment]
@daveaglick Spectre.Io 😉
