### ISSUE TITLE
GenerateFeeds should order by publish date

### ISSUE THREAD

**Issue by mholo65** [statiqdev/Statiq.Framework#92]
GenerateFeeds does not order by publish date. This is problematic if used with MaximumItems. In my case it left out the latest posts, instead of the oldest.

**Comment by daveaglick** [comment]
Agreed - since feeds are generally expected to be in descending published date, I think this can called a bug. It's sorting by input order now, so I'll make a configuration method that will preserve that behavior if anyone wants to.
