### ISSUE TITLE
OptimizeFileName strips directories

### ISSUE THREAD

**Issue by mholo65** [statiqdev/Statiq.Framework#93]
OptimizeFileName removes directories.

Problem is this:
1. Here we pull the only the filename (probably because we don't want to optimize directory names)
https://github.com/statiqdev/Statiq.Framework/blob/master/src/core/Statiq.Core/Modules/Metadata/OptimizeFileName.cs#L114
2. Here we don't append the optimized file name with old path's Directory. 
https://github.com/statiqdev/Statiq.Framework/blob/master/src/core/Statiq.Core/Modules/Metadata/OptimizeFileName.cs#L134

**Comment by daveaglick** [comment]
Found and fixed, thanks!
